package suppress

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"time"

	"push-scanner/pkg/scanner"
)

// BaselineItem represents a single suppressed false-positive or accepted risk entry.
type BaselineItem struct {
	ID          string    `json:"id"`
	Fingerprint string    `json:"fingerprint"`
	File        string    `json:"file"`
	Scanner     string    `json:"scanner"`
	Title       string    `json:"title"`
	Reason      string    `json:"reason"`
	CreatedAt   time.Time `json:"created_at"`
}

// Baseline represents the .push-scanner-baseline.json structure.
type Baseline struct {
	Version   string         `json:"version"`
	Timestamp time.Time      `json:"timestamp"`
	Items     []BaselineItem `json:"items"`
}

// ComputeFingerprint generates a stable hash for a finding to track suppressions.
func ComputeFingerprint(f scanner.Finding) string {
	h := sha256.New()
	key := fmt.Sprintf("%s|%s|%s|%s|%d", f.File, f.Scanner, f.Title, f.CWE, f.Line)
	h.Write([]byte(key))
	return hex.EncodeToString(h.Sum(nil))
}

// LoadBaseline loads suppression baseline file.
func LoadBaseline(path string) (*Baseline, error) {
	if path == "" {
		path = ".push-scanner-baseline.json"
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var b Baseline
	if err := json.Unmarshal(data, &b); err != nil {
		return nil, err
	}
	return &b, nil
}

// SaveBaseline writes findings into a baseline file.
func SaveBaseline(path string, findings []scanner.Finding) error {
	if path == "" {
		path = ".push-scanner-baseline.json"
	}
	b := Baseline{
		Version:   "0.3.0",
		Timestamp: time.Now(),
		Items:     make([]BaselineItem, 0, len(findings)),
	}

	for _, f := range findings {
		b.Items = append(b.Items, BaselineItem{
			ID:          f.ID,
			Fingerprint: ComputeFingerprint(f),
			File:        f.File,
			Scanner:     f.Scanner,
			Title:       f.Title,
			Reason:      "Baseline suppression generated by push-scanner",
			CreatedAt:   time.Now(),
		})
	}

	data, err := json.MarshalIndent(b, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}

// FilterFindings splits raw findings into active vs suppressed findings using the baseline.
func FilterFindings(b *Baseline, findings []scanner.Finding) ([]scanner.Finding, []scanner.Finding) {
	if b == nil || len(b.Items) == 0 {
		return findings, nil
	}

	suppressedMap := make(map[string]bool)
	for _, item := range b.Items {
		suppressedMap[item.Fingerprint] = true
	}

	var active []scanner.Finding
	var suppressed []scanner.Finding

	for _, f := range findings {
		fp := ComputeFingerprint(f)
		if suppressedMap[fp] {
			suppressed = append(suppressed, f)
		} else {
			active = append(active, f)
		}
	}

	return active, suppressed
}
