package scanner

import (
	"testing"
)

func TestSecretScanner(t *testing.T) {
	s := &SecretScanner{}
	opts := ScanOptions{PolicyMode: "default"}

	files := []TargetFile{
		{
			Path:               "src/config.js",
			Content:            []byte(`const awsKey = "AKIA0000000000000000"; const ghToken = "ghp_A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6Q7r8";`),
			IsStagedForPublish: true,
		},
		{
			Path:               "src/clean.js",
			Content:            []byte(`const msg = "Hello World";`),
			IsStagedForPublish: true,
		},
	}

	findings, err := s.Scan(opts, files)
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}

	if len(findings) < 2 {
		t.Errorf("Expected at least 2 secret findings, got %d", len(findings))
	}

	for _, f := range findings {
		if !f.IsHardBlock {
			t.Errorf("Secret finding %s should trigger hard block", f.ID)
		}
	}
}

func TestArtifactScanner(t *testing.T) {
	a := &ArtifactScanner{}
	opts := ScanOptions{}

	files := []TargetFile{
		{
			Path:               ".env",
			Content:            []byte("SECRET_KEY=12345"),
			IsStagedForPublish: true,
		},
		{
			Path:               "keys/private.pem",
			Content:            []byte("-----BEGIN RSA PRIVATE KEY-----"),
			IsStagedForPublish: true,
		},
	}

	findings, err := a.Scan(opts, files)
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}

	if len(findings) != 2 {
		t.Errorf("Expected 2 findings, got %d", len(findings))
	}
}

func TestSourceMapScanner(t *testing.T) {
	s := &SourceMapScanner{}
	opts := ScanOptions{}

	files := []TargetFile{
		{
			Path:               "dist/bundle.js.map",
			Content:            []byte(`{"version":3,"sources":["index.ts"]}`),
			IsStagedForPublish: true,
		},
	}

	findings, err := s.Scan(opts, files)
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}

	if len(findings) != 1 {
		t.Errorf("Expected 1 sourcemap finding, got %d", len(findings))
	}
}

func TestDependencyScanner(t *testing.T) {
	d := &DependencyScanner{}
	opts := ScanOptions{}

	files := []TargetFile{
		{
			Path:               "package.json",
			Content:            []byte(`{"dependencies": {"reqeusts": "1.0.0", "unpinned": "*", "custom": "git+https://github.com/user/repo"}}`),
			IsStagedForPublish: true,
		},
	}

	findings, err := d.Scan(opts, files)
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}

	if len(findings) != 3 {
		t.Errorf("Expected 3 dependency findings, got %d", len(findings))
	}
}

func TestAISignalScanner(t *testing.T) {
	ai := &AISignalScanner{}
	opts := ScanOptions{}

	files := []TargetFile{
		{
			Path:               "src/util.py",
			Content:            []byte("# Code generated by ChatGPT\ndef add(a, b):\n return a + b"),
			IsStagedForPublish: true,
		},
	}

	findings, err := ai.Scan(opts, files)
	if err != nil {
		t.Fatalf("Unexpected error: %v", err)
	}

	if len(findings) != 1 {
		t.Errorf("Expected 1 AI signal finding, got %d", len(findings))
	}
	if !findings[0].AISignal {
		t.Errorf("Finding should be marked as AISignal")
	}
}
